name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build DLL using Docker
      run: |
        ./build.sh

    - name: Get DLL version number
      run: |
        VERSION=$(./get_dll_version.sh)

    - name: Get DLL file path
      run: |
        DLL_PATH=$(./get_dll.sh)

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v$VERSION
        release_name: v$VERSION
        files: $DLL_PATH
        body_path: CHANGELOG.md
